// <auto-generated />
using System;
using ManagementBackend.DataModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ManagementBackend.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20251130163101_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("ManagementBackend.DataModels.Log", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<float>("CpuUsage")
                        .HasColumnType("REAL");

                    b.Property<float>("NetworkUsage")
                        .HasColumnType("REAL");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("TEXT");

                    b.Property<float>("RamUsage")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("ManagementBackend.DataModels.Node", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<float>("Cpu")
                        .HasColumnType("REAL");

                    b.Property<float>("Ram")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Nodes");
                });

            modelBuilder.Entity("ManagementBackend.DataModels.World", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Config")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Worlds");
                });

            modelBuilder.Entity("ManagementBackend.DataModels.WorldStore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("BackUpNodeIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RunningNodeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WorldStores");
                });
#pragma warning restore 612, 618
        }
    }
}
