services:
  node-backend:
    build:
      context: ../../NodeBackend/
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/sqlite.db:/flyway/sqlite.db
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
